# Generated by Django 6.1.1 on 2026-09-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.household')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='chores.chore')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.person')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chore', 'order')},
            },
        ),
        migrations.AddField(
            model_name='chore',
            name='people',
            field=models.ManyToManyField(related_name='chores', through='chores.ChoreRotation', to='chores.person'),
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.person')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('chore', 'period_start')},
            },
        ),
    ]
